---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ./external-secrets
patches:
  - target:
      group: kustomize.config.k8s.io
      version: v1beta1
      kind: Kustomization
      namespace: external-secrets
      name: external-secrets
    patch: |-
      - op: replace
        path: /helmCharts/0/version
        value: 8.3.0