---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: external-secrets
helmCharts:
  - name: kubernetes-external-secrets
    version: 8.2.0
    repo: https://external-secrets.github.io/kubernetes-external-secrets

# The source code indicates that this is an accepted field, but
# enabling this does resolve this issue. 
#
# metadata:
#   name: external-secrets
#   namespace: external-secrets